### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by sv1kwz** [johnzuidweg/Zyxel-supervisor#2]
Traceback (most recent call last):
  File "C:\2\zyxel-supervisor.py", line 1, in <module>
    import json, requests
ModuleNotFoundError: No module named 'requests'

**Comment by redhatperl123** [comment]
> Traceback (most recent call last): File "C:\2\zyxel-supervisor.py", line 1, in import json, requests ModuleNotFoundError: No module named 'requests'

Agreed, I have received this error while trying as well.

@johnzuidweg  Please look into this and provide some workaround/solution

**Comment by Danyil2710** [comment]
I have the same problem. I can't run the code. Maybe something is missing. @johnzuidweg
